name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: actions/checkout@v3
      - name: Set application properties
      - run: touch ./server/src/main/resources/application.properties
      - run: echo "${{ secrets.MAIN_APPLICATION }}" > ./server/src/main/resources/application.properties
      - run: cat ./server/src/main/resources/application.properties

      - run: touch ./server/user/src/main/resources/application-user.properties
      - run: echo "${{ secrets.USER_APPLICATION }}" > ./server/user/src/main/resources/application-user.properties
      - run: cat ./server/user/src/main/resources/application-user.properties

      - run: touch ./server/video/src/main/resources/application-video.properties
      - run: echo "${{ secrets.VIDEO_APPLICATION }}" > ./server/video/src/main/resources/application-video.properties
      - run: cat ./server/video/src/main/resources/application-video.properties

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build